# This file was generated by GoReleaser. DO NOT EDIT.
cask "falcode" do
  name "falcode"
  desc "Terminal multiplexer for multi-agent git worktree workflows"
  homepage "https://github.com/victor-falcon/falcode"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "falcode"

  on_macos do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_amd64.tar.gz"
      sha256 "4e818f1c7e43bd2f22eb79a6aa14241c93143c0ca551d2093d1ea14490fe5fb6"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_arm64.tar.gz"
      sha256 "68e1101c7d365704bb62e2fb597b2c1e51d4c939ca2dc56cb5cee27aa4b318a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_amd64.tar.gz"
      sha256 "9b0e740a6ad7595755c3df1d78c99d69e53dc2ee2597454d60cce38c633e30d2"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_arm64.tar.gz"
      sha256 "2eba748ca015faca1c0033ace61d3ff9fc07a9299126c60415ce32f1648fbfa5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/falcode"]
    end
  end

  # No zap stanza required
end
