# This file was generated by GoReleaser. DO NOT EDIT.
cask "falcode" do
  name "falcode"
  desc "Terminal multiplexer for multi-agent git worktree workflows"
  homepage "https://github.com/victor-falcon/falcode"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "falcode"

  on_macos do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_amd64.tar.gz"
      sha256 "8629785da7b60d409ff90c7bca7a3ab9a21ed2e777e22d6086e10d6133d55ce2"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_arm64.tar.gz"
      sha256 "d674e71095ab136f0cd12503447da4ee6e61e25a2e4cd172f41d0104cc846a6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_amd64.tar.gz"
      sha256 "c7d3160e522067a5630ceaaf5a3b594d7b212bb856ac0f9c545bbe05453a5387"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_arm64.tar.gz"
      sha256 "efa2d3b47ebfb23df07f7a56aba875257ab95f0bb84c8f208f578e2ddd678e72"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/falcode"]
    end
  end

  # No zap stanza required
end
