# This file was generated by GoReleaser. DO NOT EDIT.
cask "falcode" do
  name "falcode"
  desc "Terminal multiplexer for multi-agent git worktree workflows"
  homepage "https://github.com/victor-falcon/falcode"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "falcode"

  on_macos do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_amd64.tar.gz"
      sha256 "b529ed48f85ec69a962e14e89aeb4876449f8dd2ae0e450cc61b1fa28ed2eefd"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_darwin_arm64.tar.gz"
      sha256 "38c4a37a04b55fbd24541b88dab1e91278335c88a9dac108f39a0539f0fc083c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_amd64.tar.gz"
      sha256 "a9d0f7f3ce83fd0a4efe928cf05f34852f08b1fb10d7ec039d572b40c5bce266"
    end
    on_arm do
      url "https://github.com/victor-falcon/falcode/releases/download/v#{version}/falcode_linux_arm64.tar.gz"
      sha256 "120d70466933d99070cb76978c5f8cd0c9a87f564c63fc86ebe605b9183f3254"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/falcode"]
    end
  end

  # No zap stanza required
end
